version: '3'

services:
  app-car-shop:
    container_name: car_shop
    build: .
    restart: always
    volumes:
      - ./src:/app/src
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CarShop

  mongo-seed:
    container_name: seed
    build: 
      context: .
      dockerfile: Dockerfile.seed
    tty: true
    stdin_open: true
    environment:
      - MONGO_URI=mongodb://mongodb:27017/CarShop
    depends_on:
      - mongodb

  mongodb:
    container_name: car_shop_db
    image: mongo:5.0.7
    restart: always
    tty: true
    stdin_open: true
    ports:
      - 27017:27017